###
POST http://localhost:5000/api/v1/register
Content-Type : application/json

{ 
    "name" : "osama loay", 
    "email": "osamaloayyy@gmail.com", 
    "password": "12345678",
    "role": "System Admin"
}
###

POST http://localhost:5000/api/v1/otp/verify/register
Content-Type: application/json 

{
    "email" : "osamaloayyy@gmail.com" , 
    "otp" : "846734"
}

### 
POST http://localhost:5000/api/v1/login
Content-Type: application/json 

{
    "email" : "osamaloayyy@gmail.com", 
    "password" : "chingchong"
}

### 
POST http://localhost:5000/api/v1/otp/verify/login
Content-Type: application/json 

{
    "email" : "osamaloayyy@gmail.com" , 
    "otp" : "868515"
}

### 
POST http://localhost:5000/api/v1/forgotpassword
Content-Type: application/json 

{
    "email":"osamaloayyy@gmail.com"
}
###
POST http://localhost:5000/api/v1/otp/verify/forgot
Content-Type: application/json 

{
    "email": "osamaloayyy@gmail.com", 
    "newPassword" : "chingchong",
    "otp" : "124609"
}


### 
GET http://localhost:5000/api/v1/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDY0YTVmNjBkZTkwZTk2N2M1ODE1ZiIsImlhdCI6MTc0NTI0Njc1OCwiZXhwIjoxNzQ1MjUwMzU4fQ.bYRIutKfxxalGr0KUK7figok5j4952UGcv8YWweb6yo


{
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDY0YTVmNjBkZTkwZTk2N2M1ODE1ZiIsImlhdCI6MTc0NTI0Njc1OCwiZXhwIjoxNzQ1MjUwMzU4fQ.bYRIutKfxxalGr0KUK7figok5j4952UGcv8YWweb6yo",
  "user": {
    "id": "68064a5f60de90e967c5815f",
    "name": "osama loay",
    "email": "osamaloayyy@gmail.com",
    "role": "System Admin"
  }
}

### 
GET http://localhost:5000/api/v1/users/68064a5f60de90e967c5815f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDY0YTVmNjBkZTkwZTk2N2M1ODE1ZiIsImlhdCI6MTc0NTI0Njc1OCwiZXhwIjoxNzQ1MjUwMzU4fQ.bYRIutKfxxalGr0KUK7figok5j4952UGcv8YWweb6yo

{

    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDY0YTVmNjBkZTkwZTk2N2M1ODE1ZiIsImlhdCI6MTc0NTI0Njc1OCwiZXhwIjoxNzQ1MjUwMzU4fQ.bYRIutKfxxalGr0KUK7figok5j4952UGcv8YWweb6yo",
    "user": { 
    "id": "68064a5f60de90e967c5815f",
    "name": "osama loay",
    "email": "osamaloayyy@gmail.com",
    "role": "System Admin"
    }
}
### 
PUT http://localhost:5000/api/v1/users/68064a5f60de90e967c5815f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDY0YTVmNjBkZTkwZTk2N2M1ODE1ZiIsImlhdCI6MTc0NTI0Njc1OCwiZXhwIjoxNzQ1MjUwMzU4fQ.bYRIutKfxxalGr0KUK7figok5j4952UGcv8YWweb6yo

{
    
}

